/**
 * Generated by scripts/generate-sdk-types.ts.
 * Do not edit directly.
 */

import type { z } from 'zod/v4'
import type {
  SDKMessageSchema,
  SDKResultMessageSchema,
  SDKResultSuccessSchema,
  SDKSessionInfoSchema,
  SDKUserMessageSchema,
} from './coreSchemas.js'

export type SDKMessage = z.infer<ReturnType<typeof SDKMessageSchema>>
export type SDKResultMessage = z.infer<ReturnType<typeof SDKResultMessageSchema>>
export type SDKResultSuccess = z.infer<ReturnType<typeof SDKResultSuccessSchema>>
export type SDKSessionInfo = z.infer<ReturnType<typeof SDKSessionInfoSchema>>
export type SDKUserMessage = z.infer<ReturnType<typeof SDKUserMessageSchema>>
