/**
 * Generated by scripts/generate-sdk-types.ts.
 * Do not edit directly.
 */

import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js'
import type { z } from 'zod/v4'

export type AnyZodRawShape = z.ZodRawShape
export type InferShape<Schema extends AnyZodRawShape> = z.infer<z.ZodObject<Schema>>
export type EffortLevel = 'low' | 'medium' | 'high' | 'max' | 'xhigh'

export type Options = Record<string, unknown>
export type InternalOptions = Options

export type SDKSessionOptions = Record<string, unknown>
export type ListSessionsOptions = Record<string, unknown>
export type GetSessionInfoOptions = Record<string, unknown>
export type GetSessionMessagesOptions = Record<string, unknown>
export type SessionMutationOptions = Record<string, unknown>
export type ForkSessionOptions = Record<string, unknown>
export type ForkSessionResult = Record<string, unknown>
export type SessionMessage = unknown

export type Query = AsyncIterable<unknown>
export type InternalQuery = Query

export type SDKSession = {
  id?: string
}

export type McpSdkServerConfigWithInstance = {
  type: 'sdk'
  name: string
  instance?: unknown
}

export type SdkMcpToolDefinition<
  Schema extends AnyZodRawShape = AnyZodRawShape,
> = {
  name: string
  description: string
  inputSchema: Schema
  handler: (
    args: InferShape<Schema>,
    extra: unknown,
  ) => Promise<CallToolResult>
  annotations?: unknown
  searchHint?: string
  alwaysLoad?: boolean
}
