import { mkdir, writeFile } from 'fs/promises'
import path from 'path'

const root = process.cwd()

const GENERATED_HEADER = `/**
 * Generated by scripts/generate-sdk-types.ts.
 * Do not edit directly.
 */
`

const files: Record<string, string> = {
  'src/entrypoints/sdk/coreTypes.generated.ts': `${GENERATED_HEADER}
import type { z } from 'zod/v4'
import type {
  SDKMessageSchema,
  SDKResultMessageSchema,
  SDKResultSuccessSchema,
  SDKSessionInfoSchema,
  SDKUserMessageSchema,
} from './coreSchemas.js'

export type SDKMessage = z.infer<ReturnType<typeof SDKMessageSchema>>
export type SDKResultMessage = z.infer<ReturnType<typeof SDKResultMessageSchema>>
export type SDKResultSuccess = z.infer<ReturnType<typeof SDKResultSuccessSchema>>
export type SDKSessionInfo = z.infer<ReturnType<typeof SDKSessionInfoSchema>>
export type SDKUserMessage = z.infer<ReturnType<typeof SDKUserMessageSchema>>
`,

  'src/entrypoints/sdk/controlTypes.ts': `${GENERATED_HEADER}
import type { z } from 'zod/v4'
import type {
  SDKControlCancelRequestSchema,
  SDKControlInitializeRequestSchema,
  SDKControlInitializeResponseSchema,
  SDKControlMcpSetServersResponseSchema,
  SDKControlPermissionRequestSchema,
  SDKControlReloadPluginsResponseSchema,
  SDKControlRequestInnerSchema,
  SDKControlRequestSchema,
  SDKControlResponseSchema,
  StdinMessageSchema,
  StdoutMessageSchema,
} from './controlSchemas.js'
import type { SDKPartialAssistantMessageSchema } from './coreSchemas.js'

export type SDKControlCancelRequest = z.infer<ReturnType<typeof SDKControlCancelRequestSchema>>
export type SDKControlInitializeRequest = z.infer<ReturnType<typeof SDKControlInitializeRequestSchema>>
export type SDKControlInitializeResponse = z.infer<ReturnType<typeof SDKControlInitializeResponseSchema>>
export type SDKControlMcpSetServersResponse = z.infer<ReturnType<typeof SDKControlMcpSetServersResponseSchema>>
export type SDKControlPermissionRequest = z.infer<ReturnType<typeof SDKControlPermissionRequestSchema>>
export type SDKControlReloadPluginsResponse = z.infer<ReturnType<typeof SDKControlReloadPluginsResponseSchema>>
export type SDKControlRequestInner = z.infer<ReturnType<typeof SDKControlRequestInnerSchema>>
export type SDKControlRequest = z.infer<ReturnType<typeof SDKControlRequestSchema>>
export type SDKControlResponse = z.infer<ReturnType<typeof SDKControlResponseSchema>>
export type SDKPartialAssistantMessage = z.infer<ReturnType<typeof SDKPartialAssistantMessageSchema>>
export type StdinMessage = z.infer<ReturnType<typeof StdinMessageSchema>>
export type StdoutMessage = z.infer<ReturnType<typeof StdoutMessageSchema>>
`,

  'src/entrypoints/sdk/runtimeTypes.ts': `${GENERATED_HEADER}
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js'
import type { z } from 'zod/v4'

export type AnyZodRawShape = z.ZodRawShape
export type InferShape<Schema extends AnyZodRawShape> = z.infer<z.ZodObject<Schema>>
export type EffortLevel = 'low' | 'medium' | 'high' | 'max' | 'xhigh'

export type Options = Record<string, unknown>
export type InternalOptions = Options

export type SDKSessionOptions = Record<string, unknown>
export type ListSessionsOptions = Record<string, unknown>
export type GetSessionInfoOptions = Record<string, unknown>
export type GetSessionMessagesOptions = Record<string, unknown>
export type SessionMutationOptions = Record<string, unknown>
export type ForkSessionOptions = Record<string, unknown>
export type ForkSessionResult = Record<string, unknown>
export type SessionMessage = unknown

export type Query = AsyncIterable<unknown>
export type InternalQuery = Query

export type SDKSession = {
  id?: string
}

export type McpSdkServerConfigWithInstance = {
  type: 'sdk'
  name: string
  instance?: unknown
}

export type SdkMcpToolDefinition<
  Schema extends AnyZodRawShape = AnyZodRawShape,
> = {
  name: string
  description: string
  inputSchema: Schema
  handler: (
    args: InferShape<Schema>,
    extra: unknown,
  ) => Promise<CallToolResult>
  annotations?: unknown
  searchHint?: string
  alwaysLoad?: boolean
}
`,

  'src/entrypoints/sdk/toolTypes.ts': `${GENERATED_HEADER}
export {}
`,

  'src/entrypoints/sdk/settingsTypes.generated.ts': `${GENERATED_HEADER}
export type Settings = import('../../utils/settings/types.js').SettingsJson
`,
}

for (const [relativePath, content] of Object.entries(files)) {
  const target = path.join(root, relativePath)
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, content)
  console.log(`wrote ${relativePath}`)
}
